# Generated by Django 5.0.3 on 2026-02-02 15:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyQuestSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('normal', 'Normal'), ('hard', 'Hard')], max_length=10)),
                ('generated_by', models.CharField(default='logic', max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_sets', to='teams.team')),
            ],
            options={
                'db_table': 'quests_daily_set',
            },
        ),
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('normal', 'Normal'), ('hard', 'Hard')], max_length=10)),
                ('category', models.CharField(choices=[('stretch', 'Stretch'), ('muscle', 'Muscle')], max_length=10)),
                ('description', models.TextField(blank=True)),
                ('points', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'quests_quest',
                'indexes': [models.Index(fields=['difficulty', 'category', 'is_active'], name='quests_ques_difficu_c8b259_idx')],
            },
        ),
        migrations.CreateModel(
            name='DailyQuestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('daily_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='quests.dailyquestset')),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_items', to='quests.quest')),
            ],
            options={
                'db_table': 'quests_daily_item',
            },
        ),
        migrations.CreateModel(
            name='QuestCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('daily_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='quests.dailyquestitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quest_completions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'quests_completion',
            },
        ),
        migrations.AddIndex(
            model_name='dailyquestset',
            index=models.Index(fields=['team', 'date'], name='quests_dail_team_id_60c4ff_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyquestset',
            index=models.Index(fields=['date'], name='quests_dail_date_e43812_idx'),
        ),
        migrations.AddConstraint(
            model_name='dailyquestset',
            constraint=models.UniqueConstraint(fields=('team', 'date'), name='uq_daily_set_team_date'),
        ),
        migrations.AddIndex(
            model_name='dailyquestitem',
            index=models.Index(fields=['daily_set', 'sort_order'], name='quests_dail_daily_s_8a4f09_idx'),
        ),
        migrations.AddConstraint(
            model_name='dailyquestitem',
            constraint=models.UniqueConstraint(fields=('daily_set', 'sort_order'), name='uq_daily_item_set_sort'),
        ),
        migrations.AddConstraint(
            model_name='dailyquestitem',
            constraint=models.UniqueConstraint(fields=('daily_set', 'quest'), name='uq_daily_item_set_quest'),
        ),
        migrations.AddIndex(
            model_name='questcompletion',
            index=models.Index(fields=['user', 'completed_at'], name='quests_comp_user_id_13cbba_idx'),
        ),
        migrations.AddConstraint(
            model_name='questcompletion',
            constraint=models.UniqueConstraint(fields=('daily_item', 'user'), name='uq_completion_dailyitem_user'),
        ),
    ]
